name: Plugin compatibility
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build the plugin using Gradle
      run: ./gradlew buildPlugin
    - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.5
      with:
        ide-versions: |
          ideaIC:2019.1.4
          ideaIU:2019.1.4
          ideaIC:2019.3.4
          ideaIU:2019.3.4
          ideaIC:2020.1
          ideaIU:2020.1
          ideaIC:LATEST-EAP-SNAPSHOT
          ideaIU:LATEST-EAP-SNAPSHOT
